swagger: "2.0"
info:
  title: "Common Model"
  version: "1.0.0"
  description: "The common model."
  contact:
    name: "Christian Bremer"
    email: "bremersee@googlemail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
definitions:
  AccessControlEntry:
    description: "Specifies a permission and who is granted."
    type: "object"
    properties:
      permission:
        type: "string"
        pattern: "^[a-z_]+$"
        description: "Specifies the permission."
      guest:
        type: "boolean"
        default: "false"
        description: "Specifies whether anybody is granted."
      users:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Specifies the granted users."
      roles:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Specifies the granted roles."
      groups:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Specifies the granted groups."
    required:
      - "permission"
  AccessControlList:
    description: "Specifies permissions and who is granted."
    type: "object"
    properties:
      owner:
        type: "string"
        description: "The owner is always granted and can only be changed by the owner."
      entries:
        type: "array"
        items:
          $ref: "#/definitions/AccessControlEntry"
  AccessControlEntryModifications:
    description: "Specifies modifications of an access control entry."
    type: "object"
    properties:
      permission:
        type: "string"
        pattern: "^[a-z_]+$"
        description: "Specifies the permission."
      guest:
        type: "boolean"
        default: "false"
        description: "Specifies whether anybody is granted."
      addUsers:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Users to be added."
      removeUsers:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Users to be removed."
      addRoles:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Roles to be added."
      removeRoles:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Roles to be removed."
      addGroups:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Groups to be added."
      removeGroups:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Groups to be removed."
    required:
      - "permission"
  AccessControlListModifications:
    description: "Specifies modifications of an access control list."
    type: "object"
    properties:
      newOwner:
        type: "string"
        description: "The owner is always granted and can only be changed by the owner."
      entries:
        type: "array"
        items:
          $ref: "#/definitions/AccessControlEntryModifications"
  Address:
    description: "Address data."
    type: "object"
    properties:
      streetNumber:
        type: "string"
        description: "The street number."
      street:
        type: "string"
        description: "The street name."
      postalCode:
        type: "string"
        description: "The postal code."
      postbox:
        type: "string"
        description: "The postbox."
      city:
        type: "string"
        description: "The city name."
      suburb:
        type: "string"
        description: "The suburb name."
      state:
        type: "string"
        description: "The state name."
      country:
        type: "string"
        description: "The country name."
      countryCode:
        type: "string"
        $ref: "#/definitions/TwoLetterCountryCode"
      formattedAddress:
        type: "string"
        description: "The street number."
  Link:
    description: "A link description."
    type: "object"
    properties:
      href:
        type: "string"
        format: "uri"
        description: "The URI."
      type:
        type: "string"
        description: "The type."
      text:
        type: "string"
        description: "The link text."
      description:
        type: "string"
        description: "A short description."
    required:
      - "href"
  PhoneNumber:
    description: "A phone number."
    type: "object"
    properties:
      value:
        type: "string"
        description: "The phone number"
      category:
        type: "string"
        description: "The category."
    required:
      - "value"
  TwoLetterLanguageCode:
    description: "ISO 639-1 language codes from Java Locale."
    type: "string"
    enum:
      - "ar"
      - "be"
      - "bg"
      - "ca"
      - "cs"
      - "da"
      - "de"
      - "el"
      - "en"
      - "es"
      - "et"
      - "fi"
      - "fr"
      - "ga"
      - "hi"
      - "hr"
      - "hu"
      - "in"
      - "is"
      - "it"
      - "iw"
      - "ja"
      - "ko"
      - "lt"
      - "lv"
      - "mk"
      - "ms"
      - "mt"
      - "nl"
      - "no"
      - "pl"
      - "pt"
      - "ro"
      - "ru"
      - "sk"
      - "sl"
      - "sq"
      - "sr"
      - "sv"
      - "th"
      - "tr"
      - "uk"
      - "vi"
      - "zh"
  ThreeLetterLanguageCode:
    description: "ISO 639-2 language codes from Java Locale."
    type: "string"
    enum:
      - "ara"
      - "bel"
      - "bul"
      - "cat"
      - "ces"
      - "dan"
      - "deu"
      - "ell"
      - "eng"
      - "est"
      - "fin"
      - "fra"
      - "gle"
      - "heb"
      - "hin"
      - "hrv"
      - "hun"
      - "ind"
      - "isl"
      - "ita"
      - "jpn"
      - "kor"
      - "lav"
      - "lit"
      - "mkd"
      - "mlt"
      - "msa"
      - "nld"
      - "nor"
      - "pol"
      - "por"
      - "ron"
      - "rus"
      - "slk"
      - "slv"
      - "spa"
      - "sqi"
      - "srp"
      - "swe"
      - "tha"
      - "tur"
      - "ukr"
      - "vie"
      - "zho"
  TwoLetterCountryCode:
    description: "ISO 3166-1 ALPHA-2 country codes from Java Locale."
    type: "string"
    enum:
      - "AE"
      - "AL"
      - "AR"
      - "AT"
      - "AU"
      - "BA"
      - "BE"
      - "BG"
      - "BH"
      - "BO"
      - "BR"
      - "BY"
      - "CA"
      - "CH"
      - "CL"
      - "CN"
      - "CO"
      - "CR"
      - "CU"
      - "CY"
      - "CZ"
      - "DE"
      - "DK"
      - "DO"
      - "DZ"
      - "EC"
      - "EE"
      - "EG"
      - "ES"
      - "FI"
      - "FR"
      - "GB"
      - "GR"
      - "GT"
      - "HK"
      - "HN"
      - "HR"
      - "HU"
      - "ID"
      - "IE"
      - "IL"
      - "IN"
      - "IQ"
      - "IS"
      - "IT"
      - "JO"
      - "JP"
      - "KR"
      - "KW"
      - "LB"
      - "LT"
      - "LU"
      - "LV"
      - "LY"
      - "MA"
      - "ME"
      - "MK"
      - "MT"
      - "MX"
      - "MY"
      - "NI"
      - "NL"
      - "NO"
      - "NZ"
      - "OM"
      - "PA"
      - "PE"
      - "PH"
      - "PL"
      - "PR"
      - "PT"
      - "PY"
      - "QA"
      - "RO"
      - "RS"
      - "RU"
      - "SA"
      - "SD"
      - "SE"
      - "SG"
      - "SI"
      - "SK"
      - "SV"
      - "SY"
      - "TH"
      - "TN"
      - "TR"
      - "TW"
      - "UA"
      - "US"
      - "UY"
      - "VE"
      - "VN"
      - "YE"
      - "ZA"
  ThreeLetterCountryCode:
    description: "ISO 3166-1 ALPHA-3 country codes from Java Locale."
    type: "string"
    enum:
      - "ALB"
      - "ARE"
      - "ARG"
      - "AUS"
      - "AUT"
      - "BEL"
      - "BGR"
      - "BHR"
      - "BIH"
      - "BLR"
      - "BOL"
      - "BRA"
      - "CAN"
      - "CHE"
      - "CHL"
      - "CHN"
      - "COL"
      - "CRI"
      - "CUB"
      - "CYP"
      - "CZE"
      - "DEU"
      - "DNK"
      - "DOM"
      - "DZA"
      - "ECU"
      - "EGY"
      - "ESP"
      - "EST"
      - "FIN"
      - "FRA"
      - "GBR"
      - "GRC"
      - "GTM"
      - "HKG"
      - "HND"
      - "HRV"
      - "HUN"
      - "IDN"
      - "IND"
      - "IRL"
      - "IRQ"
      - "ISL"
      - "ISR"
      - "ITA"
      - "JOR"
      - "JPN"
      - "KOR"
      - "KWT"
      - "LBN"
      - "LBY"
      - "LTU"
      - "LUX"
      - "LVA"
      - "MAR"
      - "MEX"
      - "MKD"
      - "MLT"
      - "MNE"
      - "MYS"
      - "NIC"
      - "NLD"
      - "NOR"
      - "NZL"
      - "OMN"
      - "PAN"
      - "PER"
      - "PHL"
      - "POL"
      - "PRI"
      - "PRT"
      - "PRY"
      - "QAT"
      - "ROU"
      - "RUS"
      - "SAU"
      - "SDN"
      - "SGP"
      - "SLV"
      - "SRB"
      - "SVK"
      - "SVN"
      - "SWE"
      - "SYR"
      - "THA"
      - "TUN"
      - "TUR"
      - "TWN"
      - "UKR"
      - "URY"
      - "USA"
      - "VEN"
      - "VNM"
      - "YEM"
      - "ZAF"
  JavaLocale:
    description: "Java locale string representation."
    type: "string"
    enum:
      - "ar"
      - "ar_AE"
      - "ar_BH"
      - "ar_DZ"
      - "ar_EG"
      - "ar_IQ"
      - "ar_JO"
      - "ar_KW"
      - "ar_LB"
      - "ar_LY"
      - "ar_MA"
      - "ar_OM"
      - "ar_QA"
      - "ar_SA"
      - "ar_SD"
      - "ar_SY"
      - "ar_TN"
      - "ar_YE"
      - "be"
      - "be_BY"
      - "bg"
      - "bg_BG"
      - "ca"
      - "ca_ES"
      - "cs"
      - "cs_CZ"
      - "da"
      - "da_DK"
      - "de"
      - "de_AT"
      - "de_CH"
      - "de_DE"
      - "de_GR"
      - "de_LU"
      - "el"
      - "el_CY"
      - "el_GR"
      - "en"
      - "en_AU"
      - "en_CA"
      - "en_GB"
      - "en_IE"
      - "en_IN"
      - "en_MT"
      - "en_NZ"
      - "en_PH"
      - "en_SG"
      - "en_US"
      - "en_ZA"
      - "es"
      - "es_AR"
      - "es_BO"
      - "es_CL"
      - "es_CO"
      - "es_CR"
      - "es_CU"
      - "es_DO"
      - "es_EC"
      - "es_ES"
      - "es_GT"
      - "es_HN"
      - "es_MX"
      - "es_NI"
      - "es_PA"
      - "es_PE"
      - "es_PR"
      - "es_PY"
      - "es_SV"
      - "es_US"
      - "es_UY"
      - "es_VE"
      - "et"
      - "et_EE"
      - "fi"
      - "fi_FI"
      - "fr"
      - "fr_BE"
      - "fr_CA"
      - "fr_CH"
      - "fr_FR"
      - "fr_LU"
      - "ga"
      - "ga_IE"
      - "hi"
      - "hi_IN"
      - "hr"
      - "hr_HR"
      - "hu"
      - "hu_HU"
      - "in"
      - "in_ID"
      - "is"
      - "is_IS"
      - "it"
      - "it_CH"
      - "it_IT"
      - "iw"
      - "iw_IL"
      - "ja"
      - "ja_JP"
      - "ko"
      - "ko_KR"
      - "lt"
      - "lt_LT"
      - "lv"
      - "lv_LV"
      - "mk"
      - "mk_MK"
      - "ms"
      - "ms_MY"
      - "mt"
      - "mt_MT"
      - "nl"
      - "nl_BE"
      - "nl_NL"
      - "no"
      - "no_NO"
      - "pl"
      - "pl_PL"
      - "pt"
      - "pt_BR"
      - "pt_PT"
      - "ro"
      - "ro_RO"
      - "ru"
      - "ru_RU"
      - "sk"
      - "sk_SK"
      - "sl"
      - "sl_SI"
      - "sq"
      - "sq_AL"
      - "sr"
      - "sr_BA"
      - "sr_CS"
      - "sr_ME"
      - "sr_RS"
      - "sv"
      - "sv_SE"
      - "th"
      - "th_TH"
      - "tr"
      - "tr_TR"
      - "uk"
      - "uk_UA"
      - "vi"
      - "vi_VN"
      - "zh"
      - "zh_CN"
      - "zh_HK"
      - "zh_SG"
      - "zh_TW"
  JavaLocaleDescription:
    description: "A java locale and it's description."
    type: "object"
    properties:
      locale:
        $ref: "#/definitions/JavaLocale"
      description:
        type: "string"
        description: "The description of the locale."
    required:
      - "locale"
      - "description"
  JavaLocaleDescriptions:
    description: "Java locales and their descriptions."
    type: "object"
    properties:
      entries:
        type: "array"
        items:
          $ref: "#/definitions/JavaLocaleDescription"
  HttpLanguageTag:
    description: "RFC 5646 language tags from Java Locale."
    type: "string"
    enum:
      - "ar"
      - "ar-AE"
      - "ar-BH"
      - "ar-DZ"
      - "ar-EG"
      - "ar-IQ"
      - "ar-JO"
      - "ar-KW"
      - "ar-LB"
      - "ar-LY"
      - "ar-MA"
      - "ar-OM"
      - "ar-QA"
      - "ar-SA"
      - "ar-SD"
      - "ar-SY"
      - "ar-TN"
      - "ar-YE"
      - "be"
      - "be-BY"
      - "bg"
      - "bg-BG"
      - "ca"
      - "ca-ES"
      - "cs"
      - "cs-CZ"
      - "da"
      - "da-DK"
      - "de"
      - "de-AT"
      - "de-CH"
      - "de-DE"
      - "de-GR"
      - "de-LU"
      - "el"
      - "el-CY"
      - "el-GR"
      - "en"
      - "en-AU"
      - "en-CA"
      - "en-GB"
      - "en-IE"
      - "en-IN"
      - "en-MT"
      - "en-NZ"
      - "en-PH"
      - "en-SG"
      - "en-US"
      - "en-ZA"
      - "es"
      - "es-AR"
      - "es-BO"
      - "es-CL"
      - "es-CO"
      - "es-CR"
      - "es-CU"
      - "es-DO"
      - "es-EC"
      - "es-ES"
      - "es-GT"
      - "es-HN"
      - "es-MX"
      - "es-NI"
      - "es-PA"
      - "es-PE"
      - "es-PR"
      - "es-PY"
      - "es-SV"
      - "es-US"
      - "es-UY"
      - "es-VE"
      - "et"
      - "et-EE"
      - "fi"
      - "fi-FI"
      - "fr"
      - "fr-BE"
      - "fr-CA"
      - "fr-CH"
      - "fr-FR"
      - "fr-LU"
      - "ga"
      - "ga-IE"
      - "hi"
      - "hi-IN"
      - "hr"
      - "hr-HR"
      - "hu"
      - "hu-HU"
      - "in"
      - "in-ID"
      - "is"
      - "is-IS"
      - "it"
      - "it-CH"
      - "it-IT"
      - "iw"
      - "iw-IL"
      - "ja"
      - "ja-JP"
      - "ko"
      - "ko-KR"
      - "lt"
      - "lt-LT"
      - "lv"
      - "lv-LV"
      - "mk"
      - "mk-MK"
      - "ms"
      - "ms-MY"
      - "mt"
      - "mt-MT"
      - "nl"
      - "nl-BE"
      - "nl-NL"
      - "no"
      - "no-NO"
      - "pl"
      - "pl-PL"
      - "pt"
      - "pt-BR"
      - "pt-PT"
      - "ro"
      - "ro-RO"
      - "ru"
      - "ru-RU"
      - "sk"
      - "sk-SK"
      - "sl"
      - "sl-SI"
      - "sq"
      - "sq-AL"
      - "sr"
      - "sr-BA"
      - "sr-CS"
      - "sr-ME"
      - "sr-RS"
      - "sv"
      - "sv-SE"
      - "th"
      - "th-TH"
      - "tr"
      - "tr-TR"
      - "uk"
      - "uk-UA"
      - "vi"
      - "vi-VN"
      - "zh"
      - "zh-CN"
      - "zh-HK"
      - "zh-SG"
      - "zh-TW"
  HttpLanguageTagDescription:
    description: "A language tag and it's description."
    type: "object"
    properties:
      tag:
        $ref: "#/definitions/HttpLanguageTag"
      description:
        type: "string"
        description: "The description of the tag."
    required:
      - "tag"
      - "description"
  HttpLanguageTagDescriptions:
    description: "Language tags and their descriptions."
    type: "object"
    properties:
      entries:
        type: "array"
        items:
          $ref: "#/definitions/HttpLanguageTagDescription"
