swagger: "2.0"
info:
  title: "Common Model"
  version: "1.0.0"
  description: "The common model."
  contact:
    name: "Christian Bremer"
    email: "bremersee@googlemail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
definitions:
  AccessControlEntry:
    description: "Specifies a permission and who is granted."
    type: "object"
    properties:
      permission:
        type: "string"
        pattern: "^[a-z_]+$"
        description: "Specifies the permission."
      guest:
        type: "boolean"
        default: "false"
        description: "Specifies whether anybody is granted."
      users:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Specifies the granted users."
      roles:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Specifies the granted roles."
      groups:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Specifies the granted groups."
    required:
      - "permission"
  AccessControlList:
    description: "Specifies permissions and who is granted."
    type: "object"
    properties:
      owner:
        type: "string"
        description: "The owner is always granted and can only be changed by the owner."
      entries:
        type: "array"
        items:
          $ref: "#/definitions/AccessControlEntry"
  AccessControlEntryModifications:
    description: "Specifies modifications of an access control entry."
    type: "object"
    properties:
      permission:
        type: "string"
        pattern: "^[a-z_]+$"
        description: "Specifies the permission."
      guest:
        type: "boolean"
        default: "false"
        description: "Specifies whether anybody is granted."
      addUsers:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Users to be added."
      removeUsers:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Users to be removed."
      addRoles:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Roles to be added."
      removeRoles:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Roles to be removed."
      addGroups:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Groups to be added."
      removeGroups:
        type: "array"
        items:
          type: "string"
          pattern: "^[a-zA-Z0-9_-]+$"
        description: "Groups to be removed."
    required:
      - "permission"
  AccessControlListModifications:
    description: "Specifies modifications of an access control list."
    type: "object"
    properties:
      newOwner:
        type: "string"
        description: "The owner is always granted and can only be changed by the owner."
      entries:
        type: "array"
        items:
          $ref: "#/definitions/AccessControlEntryModifications"
  Address:
    description: "Address data."
    type: "object"
    properties:
      streetNumber:
        type: "string"
        description: "The street number."
      street:
        type: "string"
        description: "The street name."
      postalCode:
        type: "string"
        description: "The postal code."
      postbox:
        type: "string"
        description: "The postbox."
      city:
        type: "string"
        description: "The city name."
      suburb:
        type: "string"
        description: "The suburb name."
      state:
        type: "string"
        description: "The state name."
      country:
        type: "string"
        description: "The country name."
      countryCode:
        type: "string"
        description: "The country code."
      formattedAddress:
        type: "string"
        description: "The street number."
  Link:
    description: "A link description."
    type: "object"
    properties:
      href:
        type: "string"
        description: "The URI."
        minLength: 1
      type:
        type: "string"
        description: "The type."
      text:
        type: "string"
        description: "The link text."
      description:
        type: "string"
        description: "A short description."
    required:
      - "href"
  PhoneNumber:
    description: "A phone number."
    type: "object"
    properties:
      value:
        type: "string"
        description: "The phone number"
      category:
        type: "string"
        description: "The category."
    required:
      - "value"
  BoundingBox:
    description: "The bounding box of a geometry, feature or feature collection."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-5"
    type: "array"
    minItems: 4
    maxItems: 6
    items:
      type: "number"
  Geometry:
    type: "object"
    description: "GeoJSON Geometry"
    discriminator: "type"
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1"
    properties:
      type:
        description: "The geometry type"
        type: "string"
        enum:
          - "Point"
          - "MultiPoint"
          - "LineString"
          - "MultiLineString"
          - "Polygon"
          - "MultiPolygon"
          - "GeometryCollection"
      bbox:
        $ref: "#/definitions/BoundingBox"
    required:
      - "type"
  Position:
    description: "The first two elements are longitude and latitude."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.1"
    type: "array"
    minItems: 2
    maxItems: 3
    items:
      type: "number"
  Point:
    type: "object"
    description: "GeoJSON Point"
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.2"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            $ref: "#/definitions/Position"
  MultiPoint:
    type: "object"
    description: "GeoJSON MultiPoint"
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.3"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: "array"
            items:
              $ref: "#/definitions/Position"
  LineString:
    type: "object"
    description: "GeoJSON LineString"
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.4"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: "array"
            items:
              $ref: "#/definitions/Position"
  MultiLineString:
    type: "object"
    description: "GeoJSON MultiLineString"
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.5"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: "array"
            items:
              type: "array"
              items:
                $ref: "#/definitions/Position"
  Polygon:
    type: "object"
    description: "GeoJSON Polygon"
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.6"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: "array"
            items:
              type: "array"
              items:
                $ref: "#/definitions/Position"
  MultiPolygon:
    type: "object"
    description: "GeoJSON MultiPolygon"
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.7"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: "array"
            items:
              type: "array"
              items:
                type: "array"
                items:
                  $ref: "#/definitions/Position"
  GeometryCollection:
    type: "object"
    description: "GeoJSON GeometryCollection"
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.8"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          geometries:
            type: "array"
            items:
              $ref: "#/definitions/Geometry"
  Feature:
    type: "object"
    description: "A Feature object represents a spatially bounded thing."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.2"
    properties:
      type:
        description: "The feature type."
        type: "string"
        enum:
          - "Feature"
      id:
        description: "The identifier of this feature."
        type: "string"
      bbox:
        $ref: "#/definitions/BoundingBox"
      geometry:
        $ref: "#/definitions/Geometry"
      properties:
        description: "The feature properties."
        type: "object"
    required:
      - "type"
  FeatureCollection:
    type: "object"
    description: "A Feature Collection object is a collection of features."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.3"
    properties:
      type:
        description: "The feature collection type."
        type: "string"
        enum:
          - "FeatureCollection"
      id:
        description: "The identifier of this feature."
        type: "string"
      bbox:
        $ref: "#/definitions/BoundingBox"
      features:
        type: "array"
        items:
          $ref: "#/definitions/Feature"
    required:
      - "type"
