swagger: "2.0"
info:
  title: "common Model"
  version: "1.0.0"
  description: "The common model."
  contact:
    name: "Christian Bremer"
    email: "bremersee@googlemail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
definitions:
  Address:
    description: "Address data."
    type: "object"
    properties:
      streetNumber:
        type: "string"
        description: "The street number."
      street:
        type: "string"
        description: "The street name."
      postalCode:
        type: "string"
        description: "The street number."
      city:
        type: "string"
        description: "The city name."
      suburb:
        type: "string"
        description: "The suburb name."
      state:
        type: "string"
        description: "The state name."
      country:
        type: "string"
        description: "The country name."
      countryCode:
        type: "string"
        description: "The country code."
      formattedAddress:
        type: "string"
        description: "The street number."
  Link:
    description: "A link description."
    type: "object"
    properties:
      href:
        type: "string"
        description: "The URI."
        minLength: 1
      type:
        type: "string"
        description: "The type."
      text:
        type: "string"
        description: "The link text."
      description:
        type: "string"
        description: "A short description."
    required:
    - "href"
  PhoneNumber:
    description: "A phone number."
    type: "object"
    properties:
      value:
        type: "string"
        description: "The phone number"
      category:
        type: "string"
        description: "The category."
    required:
    - "value"
