swagger: "2.0"
info:
  title: "Api Exception Model"
  version: "1.0.0"
  description: "The response entity of exceptions."
  contact:
    name: "Christian Bremer"
    email: "bremersee@googlemail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
definitions:
  StackTraceItem:
    description: "A stack trace element of an exception."
    type: "object"
    properties:
      declaringClass:
        type: "string"
        description: "The declaring class."
      methodName:
        type: "string"
        description: "The method name."
      fileName:
        type: "string"
        description: "The file name."
      lineNumber:
        type: "integer"
        format: "int32"
        description: "The line number."
  Handler:
    description: "The handler where the exception occurred."
    type: "object"
    properties:
      className:
        type: "string"
        description: "The class name of the handler."
      methodName:
        type: "string"
        description: "The method name of the handler."
      methodParameterTypes:
        type: "array"
        items:
          type: "string"
        description: "The method parameters."
  RestApiException:
    description: "The serialized exception."
    type: "object"
    discriminator: "_type"
    properties:
      id:
        type: "string"
        description: "The id of the exception."
      timestamp:
        type: "string"
        format: "date-time"
        description: "The timestamp."
      message:
        type: "string"
        description: "A human readable exception message."
        default: "No message present."
      errorCode:
        type: "string"
        description: "A service specific error code."
      errorCodeInherited:
        type: "boolean"
        description: "Is the error code inherited from the cause?"
        default: "false"
      className:
        type: "string"
        description: "The class name of the exception."
      application:
        type: "string"
        description: "The name of the application."
      requestPath:
        type: "string"
        description: "The request path."
      handler:
        $ref: "#/definitions/Handler"
      stackTrace:
        type: "array"
        items:
          $ref: "#/definitions/StackTraceItem"
        description: "The stack trace."
      cause:
        $ref: "#/definitions/RestApiException"
