swagger: "2.0"
info:
  title: "GeoJSON Model"
  version: "1.0.0"
  description: "The GeoJSON model."
  contact:
    name: "Christian Bremer"
    email: "bremersee@googlemail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
definitions:
  BoundingBox:
    description: "The bounding box of a geometry, feature or feature collection."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-5"
    type: "array"
    minItems: 4
    maxItems: 6
    items:
      type: "number"
  Geometry:
    type: "object"
    description: "GeoJSON Geometry."
    discriminator: "type"
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1"
    properties:
      type:
        description: "The geometry type."
        type: "string"
        enum:
          - "Point"
          - "MultiPoint"
          - "LineString"
          - "MultiLineString"
          - "Polygon"
          - "MultiPolygon"
          - "GeometryCollection"
      bbox:
        $ref: "#/definitions/BoundingBox"
    required:
      - "type"
  Position:
    description: "The first two elements are longitude and latitude."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.1"
    type: "array"
    minItems: 2
    maxItems: 3
    items:
      type: "number"
  Point:
    type: "object"
    description: "GeoJSON Point."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.2"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            $ref: "#/definitions/Position"
  MultiPoint:
    type: "object"
    description: "GeoJSON MultiPoint."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.3"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: "array"
            items:
              $ref: "#/definitions/Position"
  LineString:
    type: "object"
    description: "GeoJSON LineString."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.4"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: "array"
            items:
              $ref: "#/definitions/Position"
  MultiLineString:
    type: "object"
    description: "GeoJSON MultiLineString."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.5"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: "array"
            items:
              type: "array"
              items:
                $ref: "#/definitions/Position"
  Polygon:
    type: "object"
    description: "GeoJSON Polygon."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.6"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: "array"
            items:
              type: "array"
              items:
                $ref: "#/definitions/Position"
  MultiPolygon:
    type: "object"
    description: "GeoJSON MultiPolygon."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.7"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: "array"
            items:
              type: "array"
              items:
                type: "array"
                items:
                  $ref: "#/definitions/Position"
  GeometryCollection:
    type: "object"
    description: "GeoJSON GeometryCollection."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.8"
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          geometries:
            type: "array"
            items:
              $ref: "#/definitions/Geometry"
  Feature:
    type: "object"
    description: "A Feature object represents a spatially bounded thing."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.2"
    properties:
      type:
        description: "The feature type."
        type: "string"
        enum:
          - "Feature"
      id:
        description: "The identifier of this feature."
        type: "string"
      bbox:
        $ref: "#/definitions/BoundingBox"
      geometry:
        $ref: "#/definitions/Geometry"
      properties:
        description: "The feature properties."
        type: "object"
    required:
      - "type"
  FeatureCollection:
    type: "object"
    description: "A collection of features."
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.3"
    properties:
      type:
        description: "The feature collection type."
        type: "string"
        enum:
          - "FeatureCollection"
      bbox:
        $ref: "#/definitions/BoundingBox"
      features:
        type: "array"
        items:
          $ref: "#/definitions/Feature"
    required:
      - "type"
